apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jvfce3c9t-go
  janus-idp.io/tekton: jvfce3c9t-go
  backstage.io/kubernetes-id: jvfce3c9t-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jvfce3c9t-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
